### ISSUE TITLE
 After autocomplete, the input field background is turn into white

### ISSUE THREAD

**Issue by rexpan** [creativetimofficial/blk-design-system-react#1]
# Expected Behavior

After autocomplete, the input field background should stay as same.

# Current Behavior

After autocomplete, the input field background is turn into white.

## Steps to Reproduce

![2019-03-06_10-00-59](https://user-images.githubusercontent.com/313189/53853201-16975800-3ff7-11e9-979f-d0d6509c275d.gif)

## Context

On https://demos.creative-tim.com/blk-design-system-react/

* Device: Desktop
* Operating System: Windows 10
* Browser and Version: Chrome 72

**Comment by EINazare** [comment]
Hello there, @rexpan ,

Thank you for your interest in working with our products.
Unfortunately, that is the default behavior of browsers.
I'll try to figure out a solution.

Best,
Manu
