### ISSUE TITLE
[Bug] npm run build fails with lexical error

### ISSUE THREAD

**Issue by dhyon** [creativetimofficial/blk-design-system-react#13]
### Version
latest commit
### Reproduction link
https://github.com/creativetimofficial/blk-design-system-react
### Operating System
Mac OS Mojave 10.14.4
### Device
Macbook Pro
### Browser & Version
firefox
### Steps to reproduce
1. do a fresh git clone of the repo
2. run "npm run install:clean" (be sure to change node-sass version to 4.12.0 in package.json to avoid compile error)
3. try running "npm run build"
### What is expected?
Successful build
### What is actually happening?
Creating an optimized production build...
Failed to compile.

Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: 100% - auto - 1
^.........^

---

**Comment by EINazare** [comment]
Duplicate #2
