### ISSUE TITLE
Css loads few seconds later after page reload showing just unstyled html

### ISSUE THREAD

**Issue by tashoilia** [creativetimofficial/blk-design-system-react#14]
I dont know if css transitions in the page does this but it is too slow for the first 3 seconds after page reloads.

**Comment by EINazare** [comment]
Hello there, @tashoilia ,

I've just tested this product, and it seems that everything works fine.
Please provide me some additional information.

Best,
Manu

**Comment by tashoilia** [comment]
You can check my issue on this link:  https://drive.google.com/open?id=1bJXomKPJoNZBEHUcRRjScD6sNN5MBqjC

**Comment by EINazare** [comment]
Hello again, @tashoilia ,

Does the error occur on our live preview as well: https://demos.creative-tim.com/blk-design-system-react/#/components?
I am not sure why this happens for you, I've checked with a clean install of the project on both a Windows and a Mac machines, and everything worked as expected.
My best guess is that you have something installed on either your Browser (like a plugin, or something), or on your Device that is preventing the CSS to load, or maybe you have done some changes to our project?

Best,
Manu
