### ISSUE TITLE
[Bug] Module not found: Can't resolve 'assets/css/nucleo-icons.css

### ISSUE THREAD

**Issue by Echo-Abhinav** [creativetimofficial/blk-design-system-react#18]
### Version
1.1.0
### Reproduction link
https://demos.creative-tim.com/blk-design-system-react/#/documentation/overview
### Operating System
Windows
### Device
Desktop
### Browser & Version
Does not Build
### Steps to reproduce
Following the steps provided in https://demos.creative-tim.com/blk-design-system-react/#/documentation/tutorial

I was shown the error:

./src/App.js
Module not found: Can't resolve 'assets/css/nucleo-icons.css' in 'C:\Users\MY-PC\photo-editor\src'

I have followed the instructions to fix the error but to no avail and ended up getting error like

```
error code ELIFECYCLE
error errno 1
error photo-editor@0.1.0 start: `NODE_PATH=./src react-scripts start`
error Exit status 1
error Failed at the photo-editor@0.1.0 start script.
```
I had also made a jsconfig.json file with the code:

```
{
    "compilerOptions": {
      "baseUrl": "src",
      "paths": {
        "*": ["src/*"]
      }
    }
}
```
The error persists
### What is expected?
The build to be successful
### What is actually happening?
Build Failed

---
### Solution
No clue

**Comment by EINazare** [comment]
Hello there, @KratosSparta ,

Thank you for your interest in working with our products.
I've checked our products, and it seems that we do not have any `src/App.js` file.
Please share with us the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Best,
Manu

**Comment by KratosSparta** [comment]
I followed these instructions on the website:
You can create a new react application like this
Run in terminal
npm install -g create-react-app
Go to the folder where you want to create your app
Run in terminal
create-react-app your-app-name
Navigate to your-app-name
Run in terminal
npm start
And after this, you can copy and paste anything that you want from our product (the most important is the src/assets which has all of our style, fonts and images).

so I copied the assets folder and kept in my react app after doing npm install and npm run
so after npm run, there will be a App.js in the folder and I added the import lines in the App.js file
the import lines are:
import "assets/scss/blk-design-system-react.scss";
import "assets/css/nucleo-icons.css";

I kept the assets folder outside src folder
and App.js is inside src folder

**Comment by petersonprojects** [comment]
If you set up your project directly differently than in the tutorial you can always just move the assets to where you don't have to change the path or just manually change the paths (what I did) and it works fine.
