### ISSUE TITLE
"New issue link" is broken

### ISSUE THREAD

**Issue by RobJacobson** [creativetimofficial/blk-design-system-react#27]
I attempted to submit a new issue using the "new issue link" below.  The new-issue form is broken.

Steps taken:
1. Opened "new issue link"(https://www.creative-tim.com/new-issue/blk-design-system-react) with Firefox Latest (Win 10) and spent 15 minutes typing out a detailed bug report.
2. Clicked "preview" button.

Expected result:  
Website would show a preview of my bug report, with an option to submit it.

Actual result:
The "preview" button did nothing.  No matter how many times I clicked on it, nothing happened.  Quite frustrating.  :-/

The same also occurred when I reattempted a second and third time using (a) Chrome latest and (b) Edge latest.

**Comment by RobJacobson** [comment]
Please reopen this issue. I could not submit this bug report through your form, since your form is broken. (See above.)

**Comment by rafalohaki** [comment]
I got blank website after build and serve
