### ISSUE TITLE
npm run build results a blank page

### ISSUE THREAD

**Issue by KimTrijnh** [creativetimofficial/blk-design-system-react#4]
# Expected Behavior [SOLVED]
* My site run normally with `npm start` , expect to deploy it to netlify. After `npm run build`. The 
`Live Draft URL: https://5cc74b89d69ff26092d92f15--project-huong-portfolio.netlify.com` was found blank. 
* Trying to open developer console and saw these
![image](https://user-images.githubusercontent.com/26478993/56920770-49893400-6aee-11e9-8c9f-f7b0b5c62f4e.png)

* Check build folder and found all the links were under:
`creativetimofficial/blk-design-system-react/...`

* Eventually, I found the solution for it by removing `"home": "https://github.com/creativetimofficial/blk-design-system-react/..."`
in `package.json` and would like to report this situation. Please have a look at this issue.

Thank you

# Current Behavior
After remove `"home": "https://github.com/creativetimofficial/blk-design-system-react/..."`
in `package.json` and run build again, the `creativetimofficial/blk-design-system-react` found in links in build folder are removed. Deploy works fine now. 

# Failure Information (for bugs)
Deploy page found blank with these in the console:

![image](https://user-images.githubusercontent.com/26478993/56921010-ea77ef00-6aee-11e9-9792-60ef6310f381.png)

## Steps to Reproduce

1. Clone repository
2. Install modules npm install
3. Build for production npm run build

## Context
* npm version: 6.9.0
* Operating System: Window 10
* Browser and Version:  Chrome Version 73.0.3683.103 

## Failure Logs
- netlify cli deploying informed no failure

**Comment by EINazare** [comment]
Hello there, @KimTrijnh ,

Thank you for this.
In the next update, we'll delete that from our package.json.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/


If you've liked what you saw, help me with a comment, like, share or subscribe.
