### ISSUE TITLE
What are the props on NavbarBrand doing?

### ISSUE THREAD

**Issue by tylim88** [creativetimofficial/blk-design-system-react#5]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

expecting complete documentation of component properties example:NavBarBrand

# Current Behavior

no complete documentation, not even in reactstrap official documentation
https://reactstrap.github.io/components/navbar/#app

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by tylim88** [comment]
![need doc](https://user-images.githubusercontent.com/5227509/57628572-c88d6a80-75cc-11e9-9e0e-17e984e87f5c.png)

**Comment by EINazare** [comment]
Hello there, @tylim88 ,

Thank you for your interest in working with our products.
Actually, we've done exactly what the NavbarBrand props tell us:
![Screen Shot 2019-05-13 at 6 05 55 PM](https://user-images.githubusercontent.com/26245512/57632391-383e2e00-75aa-11e9-9784-f5fc5cc2e541.png)
As you can see in the above image, on the official Reactstrap docs, it states that you can use the `tag` property to change the default `div` rendering tag of this component to something else.
We've decided to render the `NavbarBrand` as a `Link` from `react-router-dom`. When you do so, when you change the rendering tag of a component from Reactstrap, you need to add on that component, all the props that comes with the changed rendering tag, in this sample code, it is the `to` prop. Each `Link` from `react-router-dom` has to have set a `to` prop. You can read more about how to work with routing in react here: https://github.com/ReactTraining/react-router
The other tags, `data-placement`, `rel` and `title` are left there by mistake. Anyhow, all of the Reactstrap components let you add all the normal props from the html tags.

I'll add a `typo` label to this issue, and I'll delete those in our next update.

Hope this information helps you.

All the best,
Manu
ReactJS Developer at Creative-Tim.com (http://creative-tim.com/)

Trying to help the open source community:

* https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
* https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
* https://medium.freecodecamp.org/how-to-connect-a-react-design-system-with-firebase-and-redux-9646ca1c733f



* https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a
* https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx
* https://www.youtube.com/watch?v=BMPHfnAA9iI&list=PLWxSJr7LCl87rxd7A4j9WEFUbJz4gTNLa



* https://www.udemy.com/learn-reactjs-with-webpack-4-babel-7-and-material-design/
* https://www.udemy.com/how-to-use-react-with-firebase-and-redux/


If you've liked what you saw, help me with a comment, like, share or subscribe.

**Comment by tylim88** [comment]
Thank you @EINazare

Your answer is very helpful
