### ISSUE TITLE
css is getting load after js on load the page

### ISSUE THREAD

**Issue by rohitkothiya** [creativetimofficial/blk-design-system-react#6]
CSS loading after javascript on load the page

**Comment by EINazare** [comment]
Hello there, @rohitkothiya ,

Thank you for your interest in working with our products.
Please update your node and npm version to the latest.

Best,
Manu

**Comment by rohitkothiya** [comment]
Hello,
Thank you for your response for my query .
I update node version - 10.16.0 and npm version to - 6.9.0 but it  not
works fine

i faced same problem  of css load as i mention in my issue.

**Comment by EINazare** [comment]
Hello again, @rohitkothiya ,

Could you please share a video with us?

Best,
Manu

**Comment by rohitkothiya** [comment]
Hello, Thanks for your quick response.
As you requested, I attached video  where you can see the issue, when I
reload page of the app; the css is loading after js.

**Comment by EINazare** [comment]
Hello there, @rohitkothiya ,

You haven't sent any video.
Check the bellow image:
![Screen Shot 2019-06-12 at 8 42 05 AM](https://user-images.githubusercontent.com/26245512/59326069-fb22a400-8ced-11e9-8123-4b58372ecbc3.png)
Please, go on Github, and add the video there.
If Github will not accept it (this may be because of video size), use a sharing tool, such as wetransfer.

Best,
Manu

**Comment by rohitkothiya** [comment]
Hello, Thanks for your quick response.
As you requested, I attached video  where you can see the issue, when I
reload page of the app; the css is loading after js.

 link for video 
https://we.tl/t-PnZT5QzFgY

**Comment by EINazare** [comment]
Hello again, @rohitkothiya ,

I am not sure why that would happen.
If you navigate here: https://demos.creative-tim.com/blk-design-system-react/#/components
Does the issue still occur?

Best,
Manu

**Comment by rohitkothiya** [comment]
Hello, Thanks once again.
No ,there is no issue in demo that shown on your web but when i trying to
run the fresh new project locally, I face the issue.

**Comment by EINazare** [comment]
Hello again, @rohitkothiya ,

I will continue to search for a solution.

Best,
Manu

**Comment by rohitkothiya** [comment]
hello , Thanks for giving me reply continuesly on my query

Have you  reproduce this issue?
otherwise i can start with another design.

**Comment by EINazare** [comment]
Hello again, @rohitkothiya ,

I believe this is something to do with your setup.
I think you could take a look on google and see what you can do: https://www.google.com/search?q=react+css+loads+after+html&oq=react+css+loads&aqs=chrome.1.69i57j0.4911j0j7&sourceid=chrome&ie=UTF-8

Best,
Manu

**Comment by rohitkothiya** [comment]
Hi Nazare,

The solution I've applied; downgrade react-script 2.1.5 to 2.1.3. It
works fine.

Thank you so much for your help.

Regards,
Rohit

**Comment by rohitkothiya** [comment]
Hi Nazare,
while hosting the project i getting this error as shown in attached
file.and also before  downgrade version of react-scripts, i got same error
as now occurred.

**Comment by EINazare** [comment]
Hello again @rohitkothiya ,

Your files were not sent due to the fact that you've responded from your email.
Please open Github on a Browser tab and respond from there.

Best,
Manu

**Comment by rohitkothiya** [comment]
Hi Nazare,
while hosting the project i getting this error as shown in attached
image link.and also before  downgrade version of react-scripts, i got same error
as now occurred.

https://we.tl/t-cSnl4j4Tei

**Comment by EINazare** [comment]
Hello again,

Please delete the homepage prop from package.json.

Best,
Manu

**Comment by rohitkothiya** [comment]
Thank you so much for your quick response.

Can we merge these fix to master through new PR?

- Rohit

**Comment by EINazare** [comment]
Hello again, @rohitkothiya ,

Unfortunately, we need the homepage prop so that we can deploy it on github.

Best,
Manu
