### ISSUE TITLE
[Bug] npm install does not work with latest version of node node@12

### ISSUE THREAD

**Issue by RobertGossett** [creativetimofficial/blk-design-system-react#7]
### Version
Download from site on Oct 9th 2019
### Reproduction link
https://github.com/creativetimofficial/blk-design-system-react
### Operating System
Mac OS mojave
### Device
Macbook
### Browser & Version
NA
### Steps to reproduce
download
npm install
### What is expected?
install with no errors
### What is actually happening?
fs events failure (node sass root?)

---
### Solution
install with node@10
### Additional comments
~/J/blk-design-system-react-master $ npm install

> fsevents@1.2.9 install /Users/robertgossett/JPMC/blk-design-system-react-master/node_modules/chokidar/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/robertgossett/JPMC/blk-design-system-react-master/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> fsevents@1.2.4 install /Users/robertgossett/JPMC/blk-design-system-react-master/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.11.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:50:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
In file included from ../fsevents.cc:82:
../src/constants.cc:89:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagNone));
          ^
/Users/robertgossett/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/robertgossett/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:90:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSubDirs").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMustScanSubDirs));
          ^
/Users/robertgossett/Library/Caches/node-gyp/12.11.1/include/node/v8.h:3402:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/robertgossett/Library/Caches/node-gyp/12.11.1/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:82:
../src/constants.cc:91:11: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
  object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUserDropped));
          ^
/Users/robertgoss
<!-- generated by creative-tim-issues. DO NOT REMOVE -->

**Comment by EINazare** [comment]
Hello there, @RobertGossett ,

Thank you for your interest in working with our products.
Unfortunately, we cannot solve this issue. There is something about the current version of NodeJS VS LTS version of NodeJS.
If you install the LTS version of NodeJS everything will work properly.

Best,
Manu
