### ISSUE TITLE
Can't resolve '../fonts/nucleo.svg

### ISSUE THREAD

**Issue by rsRamgharia** [creativetimofficial/blk-design-system-react#8]
I saw this error from very long time, I stopped using your theme because of this kind of error, but again I download your theme and i got the same error

What is the issue is this

> ./src/assets/css/nucleo-icons.css 

> (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/assets/css/nucleo-icons.css)

Module not found: Can't resolve '../fonts/nucleo.svg' in 'F:\app\src\assets\css'

**Comment by EINazare** [comment]
Hello there, @rsRamgharia ,

Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run `npm install`
* Run `npm start`
* Showcase the issue

Best,
Manu

**Comment by xilokaine** [comment]
i got the same probleme.
