### ISSUE TITLE
[Bug] can't resolve file

### ISSUE THREAD

**Issue by talha-ah** [creativetimofficial/blk-design-system-react#9]
### Version
Latest
### Reproduction link
https://donthave.com
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome - Version 78.0.3904.97
### Steps to reproduce
Downloaded from creative-tim website
updated using npm-check-updates "ncu -u"
"npm install"
Also 
tried npm i blk-design-system-react
but it didn't work either "same error"
### What is expected?
Work.
### What is actually happening?
I download BLK React Theme and upgraded all dependencies with "ncu -u", "npm install". But when I started the server "npm start". 
I encountered this error
"./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/dots.png' in '*path*\blk-design-system-react-master\src\assets\scss'"

And Console log is 
"
blk-design-system-react.scss?v=1.0.0:4 Uncaught Error: Cannot find module './assets/img/square1.png'
    at webpackMissingModule (blk-design-system-react.scss?v=1.0.0:4)
    at Object../node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/resolve-url-loader/index.js?!./node_modules/sass-loader/lib/loader.js?!./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (blk-design-system-react.scss?v=1.0.0:4)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object../src/assets/scss/blk-design-system-react.scss?v=1.0.0 (blk-design-system-react.scss?7099:1)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Module../src/index.js (PageHeader.jsx:48)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.0 (RegisterPage.jsx:233)
    at __webpack_require__ (bootstrap:785)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
webpackMissingModule @ blk-design-system-react.scss?v=1.0.0:4
./node_modules/css-loader/dist/cjs.js?!./node_modules/postcss-loader/src/index.js?!./node_modules/resolve-url-loader/index.js?!./node_modules/sass-loader/lib/loader.js?!./src/assets/scss/blk-design-system-react.scss?v=1.0.0 @ blk-design-system-react.scss?v=1.0.0:4
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
./src/assets/scss/blk-design-system-react.scss?v=1.0.0 @ blk-design-system-react.scss?7099:1
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
./src/index.js @ PageHeader.jsx:48
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
0 @ RegisterPage.jsx:233
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1437 ./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/dots.png' in 'D:\Web\React\Themes\React\blk-design-system-react-master\src\assets\scss'
console.<computed> @ index.js:1437
handleErrors @ webpackHotDevClient.js:151
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:194
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:56
(anonymous) @ main.js:283
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:281
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
WebSocketTransport.ws.onmessage @ websocket.js:36
index.js:1437 ./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/square1.png' in 'D:\Web\React\Themes\React\blk-design-system-react-master\src\assets\scss'
console.<computed> @ index.js:1437
handleErrors @ webpackHotDevClient.js:151
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:194
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:56
(anonymous) @ main.js:283
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:281
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
WebSocketTransport.ws.onmessage @ websocket.js:36
index.js:1437 ./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/square2.png' in 'D:\Web\React\Themes\React\blk-design-system-react-master\src\assets\scss'
console.<computed> @ index.js:1437
handleErrors @ webpackHotDevClient.js:151
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:194
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:56
(anonymous) @ main.js:283
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:281
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
WebSocketTransport.ws.onmessage @ websocket.js:36
index.js:1437 ./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/square3.png' in 'D:\Web\React\Themes\React\blk-design-system-react-master\src\assets\scss'
console.<computed> @ index.js:1437
handleErrors @ webpackHotDevClient.js:151
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:194
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:56
(anonymous) @ main.js:283
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:281
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
WebSocketTransport.ws.onmessage @ websocket.js:36
index.js:1437 ./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/square4.png' in 'D:\Web\React\Themes\React\blk-design-system-react-master\src\assets\scss'
console.<computed> @ index.js:1437
handleErrors @ webpackHotDevClient.js:151
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:194
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:56
(anonymous) @ main.js:283
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:281
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
WebSocketTransport.ws.onmessage @ websocket.js:36
index.js:1437 ./src/assets/scss/blk-design-system-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/blk-design-system-react.scss?v=1.0.0)
Module not found: Can't resolve './assets/img/square5.png' in 'D:\Web\React\Themes\React\blk-design-system-react-master\src\assets\scss'
console.<computed> @ index.js:1437
handleErrors @ webpackHotDevClient.js:151
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:194
push../node_modules/sockjs-client/lib/event/eventtarget.js.EventTarget.dispatchEvent @ eventtarget.js:56
(anonymous) @ main.js:283
push../node_modules/sockjs-client/lib/main.js.SockJS._transportMessage @ main.js:281
push../node_modules/sockjs-client/lib/event/emitter.js.EventEmitter.emit @ emitter.js:53
WebSocketTransport.ws.onmessage @ websocket.js:36
webpackHotDevClient.js:65 The development server has disconnected.
Refresh the page if necessary.
"

---

**Comment by talha-ah** [comment]
[](url)
[Console log - Error - localhost-1574222778507.log](https://github.com/creativetimofficial/blk-design-system-react/files/3865421/Console.log.-.Error.-.localhost-1574222778507.log)
![Error blk-design-system-react scss](https://user-images.githubusercontent.com/49340654/69174536-06b19c80-0ad0-11ea-873f-a1ec08e92b4b.PNG)

**Comment by EINazare** [comment]
Hello there, @talha-ah ,

Thank you for your interest in working with our products.
Please provide the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run `npm run install:clean`
* Showcase the issue

You can use an online transfer tool such as https://wetransfer.com/ to share the video with us.

Waiting for the mentioned video.

Best,
Manu

**Comment by talha-ah** [comment]
Well, I followed your instructions and got this erorr.
Video Link: https://www.loom.com/share/f4dc0e565e01458f99cac20d104dd7cd

**Comment by talha-ah** [comment]
Well, I followed your instructions and now got this erorr.
Video Link: https://www.loom.com/share/f4dc0e565e01458f99cac20d104dd7cd

**Comment by EINazare** [comment]
Hello again, @talha-ah ,

Please provide the following video:
- Download the product
- Unzip the product
- Open terminal and cd into the project
- Run `npm install`
- Wait for the installation to complete
- Run `npm start`
- Showcase the issue

In my last comment, I forgot that on some Windows devices the `rm` command does not exist and an error will be thrown. So on windows devices, you need to run the install and start command separately, unless you are using a Linux terminal. I've revised the above steps by deleting the `npm run install:clean` command with the `npm install` and `npm start` ones.

I will wait for the second video. Really sorry about this.

Best,
Manu

**Comment by talha-ah** [comment]
Now I got error for node-sass.
https://www.loom.com/share/d812c0cb6c464c08816f98ee44d4096a

**Comment by talha-ah** [comment]
I have fixed the error by installing latest node-sass by running "npm install node-sass@4.13.0" and BLK is running normally. But for Argon-Design-System-React. I did the same steps as with BLK. but I got an error "TypeError:  Cannot read property 'close' of undefined". Screenshot Attached..

![Close Undefined](https://user-images.githubusercontent.com/49340654/69245581-10d9a680-0b75-11ea-9e2c-02904c3386d0.PNG)

**Comment by talha-ah** [comment]
Also my "npm start" is slow as you can see in the video. Is there any solution for that?

**Comment by talha-ah** [comment]
BLK again, After running 
1. npm install -g npm-check-updates
2. ncu -u
3. npm install
I got error. Screenshot Attached.
![BLK Error](https://user-images.githubusercontent.com/49340654/69248168-c4449a00-0b79-11ea-985e-583ebf540c39.PNG)

**Comment by EINazare** [comment]
Hello there, @talha-ah ,

Please do not change our dependencies versions. Our product will not work with them unless you make proper changes.

Best,
Manu

**Comment by asif4347** [comment]
<img width="932" alt="Screenshot 2020-03-05 at 1 16 45 PM" src="https://user-images.githubusercontent.com/20384859/75961313-95152700-5ee3-11ea-9185-0909cd5972ad.png">
having this issue again and again

**Comment by EINazare** [comment]
Hello, @asif4347 

Please make a video with the following:

* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

Best,
Manu

**Comment by kamenivskyi** [comment]
> <img alt="Screenshot 2020-03-05 at 1 16 45 PM" width="932" src="https://user-images.githubusercontent.com/20384859/75961313-95152700-5ee3-11ea-9185-0909cd5972ad.png">
> 
> having this issue again and again

Hello, did you fix this problem? I have a similar issue and don't know how to fix it. if you solved this problem, please can you tell what you did to solve this problem? Thanks anyway.

**Comment by EINazare** [comment]
Hello there, @kamenivskyi ,

You could try deleting node from your system and install it again, but you should install the LTS version.
Also, you should check that you do not have node-sass installed globally, if you do, you should unistall it, as we've seen that a lot of issues are caused by this.
You could also try installing the latest version of node-sass inside our product. We've tested the product, and on our machines, both MacOS and Windows 10, it works as expected, with no issues.

Best,
Manu

**Comment by kamenivskyi** [comment]
@EINazare Thank you! It works! 👍

**Comment by rmetel** [comment]
Hello,
i experience the same problem with relative urls for background images (../../../assets/img). I have a Spring Boot Application with a React Frontend inside ("frontend" directory in screenshot), i installed blk-design-react-system under /src/main/frontend/node_modules and i imported your css file in App.css
![project structure](https://user-images.githubusercontent.com/9657237/162333261-944a866d-4cf0-419b-ac09-cc830f81bfb0.JPG)
s
